[package]
edition = "2021"
name = "slacc"
version = "0.2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
aho-corasick = "1.1.5"
aws-lc-rs = { version = "1.18.1", default-features = false, features = [
  "alloc",
  "aws-lc-sys",
  "prebuilt-nasm",
  "ring-io",
  "ring-sig-verify",
] }
napi = { version = "3.13.0", default-features = false, features = ["napi10"] }
napi-derive = "3.6.9"
pkcs8 = { version = "0.11.0", default-features = false, features = [
  "alloc",
  "pem",
  "std",
] }
rayon = "1.12.0"
spki = { version = "0.8.0", default-features = false, features = [
  "alloc",
  "digest",
  "fingerprint",
  "pem",
  "std",
] }

[build-dependencies]
napi-build = "2.5.0"

[profile.release]
lto = true
