/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsSlacc = Slacc
export class Slacc {
  static withPatterns(patterns: Array<string>): JsSlacc
  isMatch(input: string): boolean
}
