/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AhoCorasick {
  static withPatterns(patterns: Array<string>): AhoCorasick
  isMatch(input: string): boolean
}
export type JsAhoCorasick = AhoCorasick

export declare class Signer {
  static fromPkcs8Der(suite: SignatureAlgorithmIdentifier, der: Buffer): Signer
  static fromPkcs8Pem(suite: SignatureAlgorithmIdentifier, pem: string): Signer
  get publicKey(): Buffer
  signParts(parts: Array<Buffer>, callback: ((err: Error | null, arg: Buffer) => any)): void
  signRaw(payload: Buffer, callback: ((err: Error | null, arg: Buffer) => any)): void
}
export type JsSigner = Signer

export declare class Verifier {
  static fromSpkiDer(suite: SignatureAlgorithmIdentifier, der: Buffer): Verifier
  static fromSpkiPem(suite: SignatureAlgorithmIdentifier, pem: string): Verifier
  verifyParts(signature: Buffer, parts: Array<Buffer>, callback: ((err: Error | null, arg: boolean) => any)): void
  verifyRaw(signature: Buffer, payload: Buffer, callback: ((err: Error | null, arg: boolean) => any)): void
}
export type JsVerifier = Verifier

export declare class ZipReader {
  static withDestinationPath(path: string): ZipReader
  viaBuffer(buffer: Buffer): void
}
export type JsZipReader = ZipReader

export declare function init(numThreads: number): void

export declare const enum SignatureAlgorithmIdentifier {
  Mldsa44 = 'Mldsa44',
  Eddsa = 'Eddsa',
  Rsa2048_8192 = 'Rsa2048_8192'
}
