/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AhoCorasick {
  static withPatterns(patterns: Array<string>): AhoCorasick
  isMatch(input: string): boolean
}
export type JsAhoCorasick = AhoCorasick

export declare class RsaKeyPair {
  static fromPem(pem: string): RsaKeyPair
  sign(data: Buffer, callback: ((err: Error | null, arg: Buffer) => void)): void
}
export type JsRsaKeyPair = RsaKeyPair

export declare class ZipReader {
  static withDestinationPath(path: string): ZipReader
  viaBuffer(buffer: Buffer): void
}
export type JsZipReader = ZipReader

export declare function init(numThreads: number): void
